runtime: python39  # Using Python 3.9 runtime
entrypoint: gunicorn -b :$PORT ProFileHub.wsgi:application

instance_class: F2  # Instance class, adjust based on traffic and requirements

env_variables:
  DJANGO_SETTINGS_MODULE: "ProFileHub.settings"  # Django settings module
  SECRET_KEY: "_PLACEHOLDER_"  # Placeholder for SECRET_KEY, replaced in your CI/CD pipeline
  DEBUG: "False"

handlers:
  - url: /static
    static_dir: staticfiles  # Serve static files from this directory
  - url: /.*
    script: auto  # Automatically detect WSGI entry point

automatic_scaling:
  target_cpu_utilization: 0.65  # Auto-scaling based on CPU
  min_instances: 1  # Minimum number of instances
  max_instances: 5  # Maximum number of instances

health_check:
  enable_health_check: True
  check_interval_sec: 10  # Interval for health checks
  timeout_sec: 4  # Timeout for health checks
  unhealthy_threshold: 2  # Number of failed health checks before marking unhealthy
  healthy_threshold: 2  # Number of successful health checks before marking healthy
