runtime: python39
entrypoint: gunicorn -b :$PORT ProFileHub.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: "ProFileHub.settings"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
