steps:
  # Step 1: Authenticate to Google Cloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $GCLOUD_KEY > /workspace/sa-key.json
        gcloud auth activate-service-account --key-file=/workspace/sa-key.json
        gcloud config set project $PROJECT_ID

  # Step 2: Install dependencies
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
        python manage.py makemigrations || echo "No migrations to make"
        python manage.py migrate

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/Profilehub', '.']

  # Step 4: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/Profilehub']

  # Step 5: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

timeout: '1200s'

# Substitutions for project variables
substitutions:
  _GCLOUD_KEY: $GCLOUD_KEY
  _PROJECT_ID: 'mydevportfolio-444617'

# Optional logging configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 200
