steps:
  # Step 1: Install dependencies
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
        python manage.py makemigrations || echo "No migrations to make"
        python manage.py migrate

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/Profilehub', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/Profilehub']

  # Step 4: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

  # Step 5: List Cloud Storage Buckets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'storage'
      - 'buckets'
      - 'list'

  # Step 6: List Compute Engine Instances
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'list'

timeout: '1200s'

# Optional logging configuration
options:
  logging: CLOUD_LOGGING_ONLY
  caching: DISABLED
