# Generated by Django 5.1.4 on 2024-12-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='fun_interests',
        ),
    ]
