# Generated by Django 5.1.4 on 2024-12-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_user_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
