# Generated by Django 5.1.4 on 2024-12-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_bugreport_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('bug_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PortfolioApp.bugreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
