# Generated by Django 5.1.4 on 2024-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(default='Isaac Obi Cv', max_length=100),
        ),
    ]
