name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'mydevportfolio-444617'
  GAR_LOCATION: 'us-east1'
  GKE_CLUSTER: 'django-cluster'
  GKE_ZONE: 'us-east1-b'
  DEPLOYMENT_NAME: 'django-app'
  REPOSITORY: 'django-app-repo'
  IMAGE: 'django-app-image'
  WORKLOAD_IDENTITY_PROVIDER: "principal://iam.googleapis.com/projects/90517001107/locations/global/workloadIdentityPools/github-pool-id/subject/SUBJECT_ATTRIBUTE_VALUE"

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'

    steps:
      # Checkout the repository
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      # Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'mydevportfolio-444617@appspot.gserviceaccount.com'

      # Docker Authentication for Artifact Registry
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      # Get GKE credentials
      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      # Verify Kubernetes Context
      - name: 'Verify Kubernetes Context'
        run: kubectl config get-contexts

      # Build and Push Docker Image
      - name: 'Build and Push Docker Container'
        run: |-
          DOCKER_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${GITHUB_SHA}"

          docker build -t "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      # Deploy to GKE
      - name: 'Deploy to GKE'
        run: |-
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
            django-container=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${GITHUB_SHA}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
