name: 'Deploy to Cloud Run from Source'

on:
  push: 
    branches:
      - main

env:
  PROJECT_ID: 'mydevportfolio-444617' # Your Google Cloud project ID
  REGION: 'us-east1' # Your region
  SERVICE: 'web-api' 

jobs: # all jobs  to be done 
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Check out the repository
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Step 2: Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SA_CREDS }}'

      # Step 3: Deploy to Cloud Run
      - id: deploy
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'

      # Step 4: Output the Cloud Run URL
      - name: 'Show output'
        run: echo "CLOUD_RUN_URL=${{ steps.deploy.outputs.url }}" >> $GITHUB_ENV

      # Step 5: Use the Cloud Run URL (Example)
      # Important 
      - name: 'Test Deployed Service'
        run: curl $CLOUD_RUN_URL
