name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

env:
  PROJECT_ID: 'mydevportfolio-444617'  # Your Google Cloud Project ID
  GAR_LOCATION: 'us-east1'             # Your preferred region
  GKE_CLUSTER: 'django-cluster'        # Your GKE cluster name
  GKE_ZONE: 'us-east1-b'               # Your GKE cluster zone
  DEPLOYMENT_NAME: 'django-app'        # Your Kubernetes deployment name
  REPOSITORY: 'django-app-repo'        # Your Artifact Registry repository
  IMAGE: 'django-app-image'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checkout the repository
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      # Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      # Docker Authentication for Artifact Registry
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      # Get GKE credentials
      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      # Build and Push Docker Image
      - name: 'Build and Push Docker Container'
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"

          docker build -t "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      # Deploy to GKE
      - name: 'Deploy to GKE'
        run: |-
          kubectl set image deployment/${DEPLOYMENT_NAME} \
            django-container=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
